---
- hosts: dev:#prod
  tasks:
  - name: ensure apache is running (and enable it at boot)
    service: name=apache2 state=started enabled=yes
  - name: ensure postgresql is running (and enable it at boot)
    service: name=postgresql state=started enabled=yes
  - name: ensure tomcat is running (and enable it at boot)
    service: name=bundolo-server state=started enabled=yes
  - name: ensure phantom.js script is running (and enable it at boot) TODO add it as service and enable it at boot
    debug: msg="TODO"
...