#!/bin/sh
### BEGIN INIT INFO
# Provides:          bundolo-server
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: bundolo server
# Description:       Start bundolo server
# This script will start bundolo server.
### END INIT INFO

#/etc/init.d/bundolo-server

SERVICE_NAME=bundolo-server
DAEMON=/usr/bin/java
DAEMON_OPTS="-Denv=dev -jar bundolo-server-1.2.0.jar"
PIDFILE=/tmp/bundolo-server-pid
DIRECTORY=/projects/bundolo/server

if [ ! -x $DAEMON ]; then
  echo "ERROR: Can't execute $DAEMON."
  exit 1
fi

start_service() {
  echo -n " * Starting $SERVICE_NAME... "
  start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --exec $DAEMON --chdir $DIRECTORY -- $DAEMON_OPTS
  e=$?
  if [ $e -eq 1 ]; then
    echo "already running"
    return
  fi

  if [ $e -eq 255 ]; then
    echo "couldn't start :("
    exit 1
  fi

  echo "done"
}

stop_service() {
  echo -n " * Stopping $SERVICE_NAME... "
  start-stop-daemon --stop --retry 10 --pidfile $PIDFILE --make-pidfile
  e=$?
  if [ $e -eq 1 ]; then
    echo "not running"
    return
  fi

  rm -f $PIDFILE
  echo "done"
}

status_service() {
    printf "%-50s" "Checking $SERVICE_NAME..."
    if [ -f $PIDFILE ]; then
        PID=`cat $PIDFILE`
        if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
            printf "%s\n" "Process dead but pidfile exists"
            exit 1 
        else
            echo "Running"
        fi
    else
        printf "%s\n" "Service not running"
        exit 3 
    fi
}

case "$1" in
  status)
    status_service
    ;;
  start)
    start_service
    ;;
  stop)
    stop_service
    ;;
  restart)
    stop_service
    start_service
    ;;
  *)
    echo "Usage: service $SERVICE_NAME {start|stop|restart|status}" >&2
    exit 1   
    ;;
esac

exit 0